### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tobireif** [PolymerElements/iron-swipeable-container#22]
Hi :)

What's  the license?

Tobi

**Comment by notwaldorf** [comment]
Like every other PolymerElement, the License is mentioned in bower (https://github.com/PolymerElements/iron-swipeable-container/blob/master/bower.json#L20), and at the top of every file in the repo: https://github.com/PolymerElements/iron-swipeable-container/blob/master/index.html#L3

**Comment by tobireif** [comment]
When I page-search for "license" at https://github.com/PolymerElements/iron-swipeable-container there's no match. That's inconvenient.

**Comment by notwaldorf** [comment]
Because of how many orgs/repos the code is spread across, the team manages licenses differently.

cc @azakus

**Comment by tobireif** [comment]
It would be great if the respective license would be included/linked in each README.md . (Or each repo could contain a top-level file eg "LICENSE.txt".)

cc @azakus
